---
abstract: ~
build_requires:
  Catalyst::Test: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rapid
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Plugin::Bread::Board: 0
  Catalyst::View::TT: 0
version: "\z\x01"
